name: Update README with Vercel Deploy Status

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Vercel deployment info
        id: vercel
        run: |
          # Fetch the latest deployment information from Vercel API
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" https://api.vercel.com/v6/deployments?projectId=<your-project-id>)
          url=$(echo "$response" | jq -r '.deployments[0].url')
          state=$(echo "$response" | jq -r '.deployments[0].state')
          createdAt=$(echo "$response" | jq -r '.deployments[0].createdAt')
          buildDate=$(date -d @$((createdAt/1000)) "+%Y-%m-%d %H:%M:%S")

          # Output the values for use in the next steps
          echo "::set-output name=preview_url::https://$url"
          echo "::set-output name=build_status::$state"
          echo "::set-output name=build_date::$buildDate"

      - name: Update README
        run: |
          # Replace placeholders in README with live data
          sed -i "s|<!--vercel-preview-url-->|${{ steps.vercel.outputs.preview_url }}|g" README.md
          sed -i "s|<!--vercel-build-status-->|${{ steps.vercel.outputs.build_status }}|g" README.md
          sed -i "s|<!--vercel-build-date-->|${{ steps.vercel.outputs.build_date }}|g" README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest Vercel build status"
          git push
