name: Verify Bun Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bun-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      # Install dependencies with Bun
      - name: Install dependencies
        run: bun install

      # Run the build command with Bun
      - name: Build project
        run: bun run build

      # Optionally, run tests if your build includes a testing step
      # - name: Run tests
      #   run: bun test
